# Generated by Django 3.1.6 on 2021-02-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='todo1',
        ),
    ]
